<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="properties" nsURI="http://www.novosoft.org/task/base/properties"
    nsPrefix="properties">
  <eClassifiers xsi:type="ecore:EClass" name="TaskProperties" eSuperTypes="identifiable.ecore#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//OperationType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useInPLC" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expTheshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expPeriod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actions" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fetching" eType="#//ObjectsFetchingProperties"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="#//OperationProperties"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schedule" eType="#//ScheduleProperties"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sources" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targets" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aliases" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filters" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="events" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versioned" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxVersionsCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxStorageTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Log" eSuperTypes="identifiable.ecore#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperationType">
    <eLiterals name="otBackupFull"/>
    <eLiterals name="otBackupIncremental"/>
    <eLiterals name="otBackupDifferential"/>
    <eLiterals name="otRestoreFull" literal=""/>
    <eLiterals name="otRestoreIncremental"/>
    <eLiterals name="otSynchronize"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomAction" eSuperTypes="identifiable.ecore#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ActionType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wait" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="event" eType="#//ActionRunTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="params" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActionType">
    <eLiterals name="caRunProgram"/>
    <eLiterals name="caSendEmail"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActionRunTime">
    <eLiterals name="caOnOperationStart"/>
    <eLiterals name="caOnOperationFinish"/>
    <eLiterals name="caOnOperationFailure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectsFetchingProperties" eSuperTypes="identifiable.ecore#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filesExclude" eType="#//ObjectsFetchingProperties"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filesInclude" eType="#//ObjectsFetchingProperties"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="foldersExcludeMasks" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="foldersIncludeMasks" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileFilterProperties" eSuperTypes="identifiable.ecore#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="masks" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="creation" eType="#//IntervalT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntervalT" eSuperTypes="identifiable.ecore#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower_bound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper_bound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationProperties" eSuperTypes="identifiable.ecore#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="copyMode" eType="#//CopyMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="copyDirection" eType="#//CopyDirection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diffCondition" eType="#//DiffCondition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stopCondition" eType="#//StopCondition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkFileSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkCreationTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkModificationTime"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CopyMode">
    <eLiterals name="cmSimple"/>
    <eLiterals name="cmCleanDestination"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CopyDirection">
    <eLiterals name="Direct"/>
    <eLiterals name="Reverse"/>
    <eLiterals name="Bidirectional"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StopCondition">
    <eLiterals name="scOnCriticalError" literal=""/>
    <eLiterals name="scOnAnyError"/>
    <eLiterals name="scIgnoreAllErrors"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DiffCondition">
    <eLiterals name="dcNewer"/>
    <eLiterals name="dcOlder"/>
    <eLiterals name="dcSmaller"/>
    <eLiterals name="dcLarger"/>
    <eLiterals name="dcNever" literal=""/>
    <eLiterals name="dcAlways"/>
    <eLiterals name="dcChanged"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ScheduleType">
    <eLiterals name="stOneShot"/>
    <eLiterals name="stEveryday"/>
    <eLiterals name="stWeekDays"/>
    <eLiterals name="stMonthDays"/>
    <eLiterals name="stPeriod"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScheduleProperties" eSuperTypes="identifiable.ecore#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRunMissing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ScheduleType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="days" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
</ecore:EPackage>
