
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.novosoft.task.base;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-02-09T17:25:35.952+07:00
 * Generated source version: 2.7.13
 * 
 */
public class TaskServiceClient {

    public static void main(String[] args) throws Exception {
        QName serviceName = new QName("http://base.task.novosoft.org/", "TaskService");
        QName portName = new QName("http://base.task.novosoft.org/", "TaskServiceImplPort");

        Service service = Service.create(serviceName);
        service.addPort(portName, SOAPBinding.SOAP11HTTP_BINDING,
                        "http://localhost:9090/TaskServiceImplPort"); 
        org.novosoft.task.base.TaskService client = service.getPort(portName,  org.novosoft.task.base.TaskService.class);
        
        // Insert code to invoke methods on the client here
    }

}